name: Error
description: Get help with an error or report a bug
title: "[Issue/Bug]: "
labels: ["bug"]
assignees:
  - vaporvee
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug/crash report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the Discord RPC Godot plugin are you running?
      options:
        - 1.3.1
        - 1.3.0
        - 1.2.0
        - 1.1.0
        - 1.0.1
        - 1.0.0
        - 0.3.2
        - 0.3.1
        - 0.3.0
        - 0.2.4
        - 0.2.3
        - 0.2.2
        - 0.2.1
        - 0.2.0
        - 0.1.5
        - 0.1.4
        - 0.1.3
        - 0.1.2
        - 0.1.1
        - 0.1.0
        - Custom build
    validations:
      required: true
  - type: input
    id: gd-version
    attributes:
      label: Godot Version
      description: This addon is ONLY for 4.1 and above!
      placeholder: e.g. 4.1.0-stable
    validations:
      required: true
  - type: textarea
    id: steps_reproduce
    attributes:
      label: Exact steps to reproduce this error
      description: Tell what completely exactly you did from downloading and copying the plugin to the error. You can also drag and drop a zip file of how you would setup a fresh project with it.
    validations:
      required: true
  - type: textarea
    id: gdscript
    attributes:
      label: GDScript
      description: A place for any GDScript to be formatted
      placeholder: Put in your GDScript code here and make comments with `#` to tell where wich file ends
      render: gdscript
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Godot output
      description: The output log from Godot
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: If you have anything else tell me here
      placeholder: Anything else.
    validations:
      required: false
  - type: checkboxes
    id: reinstalling
    attributes:
      label: Checks
      description: Common mistakes (Adding more in the future sorry btw)
      options:
        - label: I tried reinstalling the addon or tried to fix it myself with other methods.
          required: true
        - label: I tried restarting Discord and Godot completely.
          required: true
        - label: I did read the documentation and its troubleshooting guide https://docs.vaporvee.com/discord-rpc-godot/
          required: true
